{% set name = "dscribe" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59d7ecf66322482400664916dffac69a9b8fd77ffccf41a80ea35d8cbdc0ca21

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython >=0.29.14
  host:
    - python
    - pip
    - pybind11
  run:
    - python
    - pip
    - pybind11
    - numpy
    - scipy
    - ase
    - scikit-learn
    - joblib

test:
  imports:
    - dscribe
  commands:
    - pip check

about:
  home: https://singroup.github.io/dscribe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DScribe is a python package for creating machine learning descriptors for atomistic systems.

  description: |
    DScribe is a Python package for transforming atomic structures into
    descriptors that can be used in various machine learning tasks related
    to materials science.
  doc_url: https://singroup.github.io/dscribe/
  dev_url: https://github.com/SINGROUP/dscribe

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
