{% set name = "dscribe" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 444484b7070255257383d191936f8bb5e4b11c1ba8eb4ac22c7273e82f9c8bdd

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython >=0.29.14
  host:
    - python
    - pip
    - pybind11
    - setuptools
  run:
    - python
    - pip
    - pybind11
    - numpy
    - scipy
    - ase
    - scikit-learn
    - joblib
    - sparse

test:
  imports:
    - dscribe
  commands:
    - pip check

about:
  home: https://singroup.github.io/dscribe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: DScribe is a python package for creating machine learning descriptors for atomistic systems.

  description: |
    DScribe is a Python package for transforming atomic structures into
    descriptors that can be used in various machine learning tasks related
    to materials science.
  doc_url: https://singroup.github.io/dscribe/
  dev_url: https://github.com/SINGROUP/dscribe

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
