{% set name = "dscribe" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98afaea665093a8cdf2ccf34cdeb961632fbff2d007de4a8e533c8029d350afd

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pybind11
    - python
    - pip
  run:
    - pybind11
    - python
    - pip
    - numpy
    - scipy
    - ase
    - scikit-learn
    - joblib

test:
  imports:
    - dscribe
    - dscribe.libacsf.acsfwrapper
    - dscribe.libmbtr.mbtrwrapper
  commands:
    - pip check

about:
  home: https://singroup.github.io/dscribe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'DScribe is a python package for creating machine learning descriptors for atomistic systems.'

  description: |
    DScribe is a Python package for transforming atomic structures into
    descriptors that can be used in various machine learning tasks related
    to materials science.
  doc_url: https://singroup.github.io/dscribe/
  dev_url: https://github.com/SINGROUP/dscribe

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
