{% set name = "dscribe" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fd850ef7f0f838ad68fe0643094c6bdf9efe5714be00156e9ae2cc0afc97fd3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - ase
    - scikit-learn
    - joblib

test:
  imports:
    - dscribe

about:
  home: https://singroup.github.io/dscribe/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'DScribe is a python package for creating machine learning descriptors for atomistic systems.'

  description: |
    DScribe is a Python package for transforming atomic structures into
    descriptors that can be used in various machine learning tasks related
    to materials science.
  doc_url: https://singroup.github.io/dscribe/
  dev_url: https://github.com/SINGROUP/dscribe

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
