travis:
  secure:
    BINSTAR_TOKEN: VxHdB/DqzP5qsiA8y9cKaa6rGwQDHvwpSD3s2cNBLRMszROn6lGJZUBNpz0nfj5s0mRVV/okdUJwASssCj5SOrumqHAv3tF7+3ihBuKVOEeGiLRVBawLbNZUYMlO1JY9vdcjagErnXC+Svgj9C+ERkL8zskY16LCS3ES8ngmkxpmK6/USEHUJorzhvXCZfZPmxIbrO4lyDyz8sh+5xq03wgWOQY2/NSs5Dp8Sm8Ibz/mMLwQamCptw2L5D9AXveeXcefMGHMCu9XEXXB62QHJYgQEFSrvrVcsUDVvRqfH4C2CqJRIl8c40C/WPfs6PN/X5EyNmlvA94nGXe0E5fWInPA4fA0clBgq6PgQ77ujZ3LBGn0zExbIkuSiDo20zjN4V4EV7LGtTesZRdW6Qt7OOLbs2LLCiNb0Ne/YpuUUpWrntd0VcDpRNN7RmTdwOZE0KYLjuO9oiVjkr0iakpbGjx1PmAa2s+ycrAGJBFwJ1ft4m5QWPfWvBaz9CDfsAXS6SHznzxxEn1W7RhewjVTt1/ejInP2eAUQBe000G/ww+BN6VX2lnZMv4EsH0Hy41huSv4b2HbWHQdTU1ZGzl4fipKchqG+GrzMLC8gpsjTxlr22o9UTLMLTvgD6rItV1PJdbYlrFalA+mKKQDXLfJfTYX/c2tL2mfKKk5ArRzvdU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
